### ISSUE TITLE
Parámetros configuración carga de ficheros

### ISSUE THREAD

**Issue by JJAM2019** [renderpci/dedalo#19]
Hola,

Estamos teniendo problemas con la configuración del Sistema a la hora de poder cargar imágenes, videos, … Nos muestra un límite de 2MB.
Por favor, ¿podrías indicarnos qué parámetros tenemos que configurar para aumentar esa limitación?
 
Hemos subido el valor en upload_max_filesize del php.ini pero parece que no tiene efecto.

Un saludo y gracias por la ayuda

**Comment by renderpci** [comment]
Hola / hi

The question was: We have problems with the Dédalo configuration for upload image and video files,... Dédalo show a 2MB limit.

Can you tell me that parameters need to config to change this limitation.

We change the upload_max_filesize in the php.ini but don't has effect.

**Solución en Castellano:**
En php.ini hay dos parámetros:
 
- upload_max_filesize
- post_max_size
 
Los dos tienen que tener el máximo tamaño de fichero que queréis configurar. Ejemplo: 4 GB

Recuerda recargar php para que los parámetros se activen.

**Solution in English:**
In php.ini you need change two parameters.

- upload_max_filesize
- post_max_size
 
both need has the max file size  that you want to change. ex: 4GB.

Remember reload php to take effect

Alex

**Comment by JJAM2019** [comment]
Thanks, Alex

We have updated the two parameters and now the upload limits have changed. 

But when we try to upload a video,  Dedalo returns an error:  "Error. Invalid received data".

Moreover, when we play the video shows another message "Sorry. Unplayable media"

Could you help us?

Regards

**Comment by renderpci** [comment]
Hi

will be great if you can put the error_log of the php, because the error is too ambiguous.

Two things to see:
**1  External libs:**

Test the installation libs and versions: (you can use the Dédalo admin ) 
<img width="171" alt="screenshot 2019-02-05 at 17 07 26" src="https://user-images.githubusercontent.com/8447635/52286573-ba460780-2968-11e9-992b-c1535e67b93c.png">

- ffmpeg ver ???

<img width="198" alt="screenshot 2019-02-05 at 17 07 50" src="https://user-images.githubusercontent.com/8447635/52286598-c3cf6f80-2968-11e9-80c1-dd1064a45558.png">

- Probe ver ???

<img width="236" alt="screenshot 2019-02-05 at 17 07 56" src="https://user-images.githubusercontent.com/8447635/52286610-c762f680-2968-11e9-8ed8-9055a49626ba.png">

- qt-faststart ver ???

<img width="219" alt="screenshot 2019-02-05 at 17 08 02" src="https://user-images.githubusercontent.com/8447635/52286616-c9c55080-2968-11e9-8b53-ef3a394b2db5.png">

**2 Media permisions**

check the 'media' directory permissions, be sure that Dédalo can read / write / execute

Best

**Comment by JJAM2019** [comment]
Hi,

We have reviewed every file that you said: ffmpeg, probe, qt-faststart. 
All of them have the same version. 
Also, the media directory has the correct permission to read, write and execute.

![image](https://user-images.githubusercontent.com/16013864/52335386-93d4aa80-2a02-11e9-80ee-4565265e8c3b.png)

We attach the php_error.log but, we don't see any reference to the problem with the media files.

[php_error.log](https://github.com/renderpci/dedalo/files/2835897/php_error.log)

Regards

**Comment by renderpci** [comment]
Hi

Two things:

**1 OCI8:** the error in the log is only a warning and I think that is not a Dédalo problem is a php installation problem.

[14-Jan-2019 11:40:40 UTC] PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib64/php/modules/oci8.so' - /usr/lib64/php/modules/oci8.so: cannot open shared object file: No such file or directory in Unknown on line 0

Say that you are using Oracle module, oci8, but you don't load it (or you don't has the library in the php modules).
If you want use Oracle (Dédalo don't need it, but you can use it only for publication) you need config / install the php to load the oci8 module correctly, if not, remove it from your installation.

but this warning is not critical.

**2 Check the permissions of the php:**

run this command (normal ffmpeg command) with the php user ( you can see the php user in the Dédalo admin panel)

<img width="190" alt="screenshot 2019-02-06 at 12 33 53" src="https://user-images.githubusercontent.com/8447635/52338775-9c7dae80-2a0b-11e9-9100-f4e58ceb3e5c.png">

with the php user, like: "usr_dedalo" or "render" in my screenshot (change it with your php user) exec in terminal this commands:

su usr_dedalo
nice /usr/local/bin/ffmpeg

You need see that the php user can run ffmpeg.

**3 check if the php user can access to the /media/av/ folder**

with the php user (see it in the point 2) exec in terminal this commands into the dedalo/media/av/original

su usr_dedalo

cd  .../dedalo/media/av/original
mkdir test
rm -d test

(you can check all directories inside /media/av like 204,404,576, etc)

if you don't see any error you have permissions if not change it.

**4 check the upload temp directory**

When you upload the video file, Dédalo need store it in a temp directory, you can see this in the upload tool:

<img width="473" alt="screenshot 2019-02-06 at 12 51 56" src="https://user-images.githubusercontent.com/8447635/52340760-ea48e580-2a10-11e9-9f62-4f52d729b73d.png">

If you see the warning message, check the temp permissions. 

I hope this can help...

Best

**Comment by JJAM2019** [comment]
Hi, 

We attach a video with more information about the issue.

[Dedalo issue.zip](https://github.com/renderpci/dedalo/files/2839670/Dedalo.issue.zip)

As you will see, the permissions are fine. The video uploads to the server and it converts to another format. Even, we can play the video uploaded.

But We don't know why Dedalo shows the error message "Invalid received data".

Regards

**Comment by renderpci** [comment]
Hi

I can't reproduce this error, and is evident that something happen between the server and client connection. Seem like the client lost the connection and don't receive the ok from the server:
Can you say me the Chrome version that you are using? (maybe the error is a problem with specific Chrome version)

Best

**Comment by renderpci** [comment]
Hi

I think that I found you error, please check if you can create a posterframe of your video:

Select the video field and run the tool "Posterframe":

<img width="155" alt="screenshot 2019-02-11 at 09 41 08" src="https://user-images.githubusercontent.com/8447635/52552676-5cd70e00-2de1-11e9-8e4b-cc3058004d2f.png">

in the tool create the posterframe:

<img width="1145" alt="screenshot 2019-02-11 at 09 41 53" src="https://user-images.githubusercontent.com/8447635/52552701-8132ea80-2de1-11e9-9a71-67feebb195c3.png">

<img width="172" alt="screenshot 2019-02-11 at 09 41 57" src="https://user-images.githubusercontent.com/8447635/52552706-85f79e80-2de1-11e9-9463-622e019359a0.png">

If your installation don't work, check the libs:

/lib/Zend

You will need:

-Bit/
Exception.php
-IO/
-Media/
-Mime/

If you loosed some of this libs, use the libs in the .zip:

[Zend.zip](https://github.com/renderpci/dedalo/files/2850287/Zend.zip)

And try if the error disappear.

Best

**Comment by JJAM2019** [comment]
Hi,

I have tried to create the "Posterframe" and I have achieved it without problems.

Our chrome version is 72.0.3626.96 (Build official) (64 bits)

Thanks.

Regards

**Comment by renderpci** [comment]
Hi

Is not a problem with Chrome, we are trying with this version and all work ok.

Can yo make this command in the terminal server with the php_error_log of your installation:
` tail -f php_error_log`

After reproduce the error in Dédalo and send me the result.

Best

**Comment by renderpci** [comment]
I close this issue because it has been inactive for a long time ...
