### ISSUE TITLE
Numisdata ontology in Dédalo

### ISSUE THREAD

**Issue by Marleen-77** [renderpci/dedalo#33]
Hi Alex,
After Manuel's instructions about Numisdata yesterday, we have one question that we hope you can help us with. We succeeded in installing the Numisdata ontology in Dédalo, but it still looks a bit different from the TEST version we worked in yesterday. We can still see much more of the 'normal' Dédalo environment. For example, under 'catalogue' we still have to click through 'cultural' > 'material' > 'moveable heritage' etc. before getting to the parts of Numisdata that are relevant to us (mints, types, archive etc.). In the TEST version, these show up immediately when clicking 'catalogue': 
![image](https://user-images.githubusercontent.com/75026956/100237768-a7cb0280-2f2f-11eb-9c74-bd2589bf9aaa.png)

How do we change this? I hope you can help us with this!

All best,
Marleen (also on behalf of Ivan)

**Comment by renderpci** [comment]
Hi Marleen.

Yes you can change the path in the menu changing the config4.php and the config4_areas.php files.

for config4.php you need find the 'DEDALO_ENTITY_MENU_SKIP_TIPOS' constant and replace with:

```
define('DEDALO_ENTITY_MENU_SKIP_TIPOS', serialize( array('dd355','dd349','dd322','numisdata1')));
```

for the config4_areas.php you need add this lines:

```
# DEFAULT DENY AREAS

$areas_deny[] = 'dd69';
$areas_deny[] = 'dd222';
$areas_deny[] = 'dd137';
$areas_deny[] = 'rsc1';	
$areas_deny[] = 'dd356'; 
$areas_deny[] = 'dd321'; 
$areas_deny[] = 'dd351'; 
$areas_deny[] = 'dd354'; 
$areas_deny[] = 'dd323';
$areas_deny[] = 'numisdata276'; 
$areas_deny[] = 'rsc179'; 
$areas_deny[] = 'oh80';
$areas_deny[] = 'dd606';
```

I hope that it will be clear, if not, don't hesitate to ask me.

Alex

**Comment by Marleen-77** [comment]
Thanks for your quick response, I think this should work fine!
