### ISSUE TITLE
Problem with upddate to version 5.7.3

### ISSUE THREAD

**Issue by pricua** [renderpci/dedalo#34]
Hi,

We are trying to upgrade a Dedalo installation from version 5.5.37 to version 5.7.3.

Previously we had already successfully updated this same installation.

We have replaced the files on disk and added the new variables to the config file and when accessing Dedalo it already indicates that it is version 5.7.3.

Then we have updated the data version to 5.6.0, checking that the new properties column of type jsonb has been correctly added to the jer_dd table.

But the last part of updating the structure is failing us. The files are downloaded correctly in the directory lib/dedalo/backup/backups_structure/ srt_download but an error is occurring with the import of the file dedalo4_development_str.custom.backup

We have tried to manually launch the pg_restore command from command line and we get the following error "pg_restore: [archiver] unsupported version (1.14) in the file header"

Investigating the error it seems that it is because the file has been generated with a later version of PostgreSQL.

On the server we have version 10.16 installed. Is there any way to import the file into pgsql 10 or is this version of pgsql no longer valid for the latest version of Dedalo?

Or it may be that we need to carry out a previous configuration step?

I don't know if a similar case has happened to you or has been reported to you.

I hope you can help us with this

**Comment by renderpci** [comment]
Hi Pricua

Yes, the copy versions of the ontology are from/to PostgreSQL 12+. But you can use the json version for import the ontology into PostgreSQL v10+ (all supported versions of PostgreSQL can use the json file)

Get the file here:
`dedalo/install/import/ontology/json_file/`

and use the 'Import ontology json' process into the administration tool.

I hope it's clear.

**Comment by pricua** [comment]
Hi renderpci,

Perfect. Using 'Import ontology json' I have been able to import the ontology correctly.

Thanks for the help!
