### ISSUE TITLE
Print templates error

### ISSUE THREAD

**Issue by JJAM2019** [renderpci/dedalo#39]
Dear All,

This issue is related to the #38. We still experience some issues with the print templates: 
When we try to print, Dedalo returns one error “Sorry. Error was found on render pdf file. See the log for more info “. 

You can found the log and the capture of the error screen attached to this ticket.

[print_error](https://user-images.githubusercontent.com/16013864/118446658-2be89080-b6f0-11eb-98cc-d5be870bd13a.png)
[Error plantillas impresion Dedalo.txt](https://github.com/renderpci/dedalo/files/6491855/Error.plantillas.impresion.Dedalo.txt)

Also, we can’t delete any template. There isn’t any button or command to do it.

Thanks a lot for your time. Regards.

**Comment by renderpci** [comment]
Dear JJAM2019

For delete the templates. (Note that you can not delete the "Default templates" only the "Custom templates" the user templates that you can create).

1- Make sure you are updated to the latest version of Dédalo (currently 5.8.1).

2 -Check user permissions in profile -> tools :

<img width="127" alt="PastedGraphic-3" src="https://user-images.githubusercontent.com/8447635/119364593-579ae600-bcaf-11eb-9869-704e4ce35538.png">

3 - Tool Layout Print page must show Custom and Default templates in this way and you could create and delete custom templates as you need: 

<img width="640" alt="PastedGraphic-1" src="https://user-images.githubusercontent.com/8447635/119364644-641f3e80-bcaf-11eb-8101-88051668d526.png">

Or if you want delete the templates manually in the section template, you can go to the:

System adminitration -> Layout -> Layout
or 
Layout templates

<img width="393" alt="Screenshot 2021-05-24 at 16 52 42" src="https://user-images.githubusercontent.com/8447635/119365707-806fab00-bcb0-11eb-8216-44398639d2fc.png">

And use the delete button in the list:

<img width="98" alt="Screenshot 2021-05-24 at 16 53 30" src="https://user-images.githubusercontent.com/8447635/119365912-b876ee00-bcb0-11eb-8ab0-da0b340ddbb4.png">

I hope that this information will be useful to you.

Best
