### ISSUE TITLE
Update to V.5.8.2

### ISSUE THREAD

**Issue by pricua** [renderpci/dedalo#40]
We are having problems updating to version 5.8.2 (from version 5.7.72). Specifically in the step "update data version: 5.6.1 -> 5.6.2", where checks and updates the values of table 'matrix_activity'.

After more than 12 hours the process ends without reporting any errors and the update is not performed.

Is there a log where the process is being recorded or where the result can be checked?

In the release notes you state:
This update review all the activity data and could be a long process, it can take some hours or days (if you have more than 30.000.000 records in activity).

In our case, the matrix_activity table has more than 45,000,000 records.

Have you tried to update on an installation with so much data? Do I have to do any special configuration in apache or postgres for the process to work?

Thanks in advance!

**Comment by renderpci** [comment]
Hi Pricua

The process to update data to 5.6.2 version with large databases could be very long and it will need resources. If you have a large table maybe you need assign more RAM to PHP and postgreSQL.

Can you say the amount of RAM and the server aspects (SO, processors and HD) that you will use to do the update?

Best

**Comment by pricua** [comment]
Hi renderpci,

the amount of RAM is 16GB and 5GB for Memory Swap.

The server is Centos 7 with 8 Intel(R) Xeon(R) Gold 6143 CPU @ 2.80GHz processors of 4 cores each. Has 22GB free HD.

It is enough to do the update?

Best

**Comment by renderpci** [comment]
Hi Pricua

You server don't has enough resources to process the 45.000.000 records. With this amount of RAM PHP will be exhausted and will stop the process. I recommend you that change the php.ini to increase the php ram to 8GB or 10GB, but it's possible that these change not would be enough.
But
The good news are; you can repeat the process!, the records done are marked and the update don't start from the begin!. You can try to update 3 or 4 times and the update check if the record was processed, and if it's marked, it will not apply update again.
summary:
1 try to increment the RAM to php
2 try to update 3 or 4 times (or more)

I hope that this explanation helps you.
Best

**Comment by pricua** [comment]
Hi,

Thanks so much for the explanation.

We have tested it in a smaller installation and repeating the process twice it has been perfect.

During the weekend we will test it in the installation of the 45.000.000 records.

Now when we are able to continue with the process, we have another question. It is in the data update 5.8.0 -> 5.8.2. The message "Important! Before run this update, you must update your ontology version to 05-19-2021 or later" appears and does not allow the update.

We have updated the ontology with the json file (dedalo/install/import/ontology/json_file/structure.json) that incorporates the new version 5.8.2, but it is only updated on 03-22-2021.

We have also looked for it directly in the master branch but it is not up to date either. It is a 4-month-old version compatible with version 5.8.0 (the rest of the folders in  dedalo/install/import/ontology directory have been updated 16 days ago to be compatible with version 5.8.2)

Could you also update this file in order to update the ontology and complete the update to version 5.8.2?

Thank you very much again!

**Comment by renderpci** [comment]
Hi Pricua

Upss, the json version of ontology was not update because the format was changed to .zip (and I don't include it to my .gitignore file :-) )

Now, it's ready.

Best

**Comment by pricua** [comment]
Perfect!

We have everything updated correctly to version 5.8.2.

You can now close the issue.

Best,

**Comment by renderpci** [comment]
Hi Pricua!

Ok, I glad you can update

I close this issue

Best
