### ISSUE TITLE
Update to 5.8.2 - Language problem

### ISSUE THREAD

**Issue by ritmele** [renderpci/dedalo#41]
After updating to version 5.8.2 the API is not providing the contents in Valencian language.

**Comment by renderpci** [comment]
Hi Ritmele

We are fixing the problem, the API has control about the languages and Valencian language code it's more longer than English, Spanish, French..., the code for Valencia is lg-vlca while the Spanish is  lg-spa (one letter less)

Ok, If you want to fix the problem before we build the update, you can change in the file:

`../lib/dedalo/publication/server_api/v1/common/class.web_data.php`

in the line 229 inside the case 'lang':

Change:
`preg_match('/^lg-[a-z]{2,3}$/i', $value, $output_array);`

to:
`preg_match('/^lg-[a-z]{2,5}$/i', $value, $output_array);`

I think that this will help to solve the problem.

Best
Alex
