### ISSUE TITLE
Getting fatal error almost finishing installation of DEDALO v5.8.3

### ISSUE THREAD

**Issue by FelipeBergua** [renderpci/dedalo#43]
Hi,
This is the error we get in the web browser trying to finish Dedalo installation:
<img width="617" alt="error" src="https://user-images.githubusercontent.com/38144118/145429145-486edb50-692f-492a-8d16-097c111ac950.png">
I think our server configuration is completed but I'm not sure after this.
We ask for help. Thanks for any comment.

**Comment by renderpci** [comment]
Hi FelipeBergua

1 For the first 2 errors (red boxes): seems that you don't have installed the Postgres module for PHP:

https://www.php.net/manual/en/function.pg-query.php

If you are using Ubuntu you can try to install it with:

`apt install php8.0 php8.0-pgsql`

Maybe you forgot other modules and will need install them, you can try to install all modules that Dédalo will need with:

`apt install php8.0 php8.0-cli php8.0-common php8.0-mysql php8.0-pgsql php8.0-gd php8.0-mbstring php8.0-xml php8.0-pspell php8.0-tidy php8.0-bcmath php8.0-imap php8.0-soap php8.0-opcache php8.0-fpm php8.0-zip php8.0-curl`

2 The 3 error say that the 'config_auto.php' file do not exist. The config_auto.php file is created by the install script and save in the ..dedalo/lib/dedalo/config directory, if the install script can not save this file in the config directory you will get this error. Maybe you need to review the permisions for php / apache user to read/ write inside Dédalo tree.

Some commands that could be useful:

```
chown -R my_user ../httpdocs/
chgrp -R my_group ../httpdocs/
chmod -R 755 ../httpdocs/
```

I hope that this explanations can help you.
Best

**Comment by FelipeBergua** [comment]
Thank you very much. I can now continue with the installation. 
;)
