### ISSUE TITLE
"ERR_TOO_MANY_REDIRECTS" executing Dedalo v5.8.3 for the first time

### ISSUE THREAD

**Issue by FelipeBergua** [renderpci/dedalo#44]
Hi,
We can't set de root password at this point (image below) when set de web browser direction at https://dedalo.wondercoins.es/lib/dedalo/install/index.php
<img width="1167" alt="root-pass" src="https://user-images.githubusercontent.com/38144118/145730750-28d87bc9-5272-4ec4-b203-2501b9d6599b.png">

We've got the same kind of error when access to https://dedalo.wondercoins.es/index.php
<img width="1132" alt="too_many_redirects" src="https://user-images.githubusercontent.com/38144118/145730783-c921477a-da33-429a-b126-93ca5421c871.png">

We ask for your help. Thanks for any comment.

**Comment by renderpci** [comment]
Hi FelipeBergua

Seems like you don't have the tld in the install that Dédalo want to open.

We detect a error in the install version 20 days ago, and maybe you are affected by it:
https://github.com/renderpci/dedalo/commit/9bebc974492c9ba9fe6cedfd4e02c80d9669d950

Maybe you could update your code with the master version and try again.

If this action not work, questions:

> What exactly is the version that you are installing?
> Do you have the last one?

And remember update the ontology in the tool_administration, after set root pw but before you re-login with the new pw.

<img width="235" alt="Screenshot 2021-12-15 at 15 49 31" src="https://user-images.githubusercontent.com/8447635/146208341-eb48df01-aa5b-4a6b-b5f2-b59932cd0d40.png">

I hope that this Information is clear.

Best

**Comment by FelipeBergua** [comment]
Hi,
It works!
I have now de root password already set.
But I have a doubt with de ontology update befor re-login. ¿where is the tool_administration you mentioned?
Thanks

**Comment by renderpci** [comment]
Great!

When you are install Dédalo, it will answer about the root pw then you will need to login with the root account, the first page that you will see is the tool_administration, in these point you need to update the ontology with the button: "Update structure". The screen looks that:

<img width="1175" alt="Screenshot 2021-12-16 at 10 06 06" src="https://user-images.githubusercontent.com/8447635/146341920-146b5156-f07c-4a35-aac0-7e32f8a1f4a1.png">

In this point is important to press the button "Update structure" and see the two green alerts before re-login. It ensure that you will have the correct ontology for you configuration.

Best
