### ISSUE TITLE
How to change RAM requirements used by PHP and PostgreSQL in the virtual machine for developers.

### ISSUE THREAD

**Issue by jgomcat** [renderpci/dedalo#46]
When I changed the RAM requirements (from 8GB to 4GB) used by PHP and PostgreSQL in the virtual machine for developers 
(see https://dedalo.dev/v5#dd1100_1890), I lost access to the Dédalo interface used to manage heritage data (http://localhost/dedalo):

![Error_conexión](https://user-images.githubusercontent.com/97663934/149300536-7dcdff63-4e25-4c81-9019-96a432c621a9.jpg)
Ops.. [Exception] Error. Could not connect to database (52).

I just changed the /etc/postgresql/14/main/postgresql.conf file.

![PostgreSQL_Shared_Buffers](https://user-images.githubusercontent.com/97663934/149299665-efc0e042-619b-4f4d-9023-88e0422e5014.jpg)

I don't know if the PHP /etc/security/limits.conf file should also be modified.

Help, please.
Thank you very much.

**Comment by renderpci** [comment]
Hi jgomcat

The virtual machine has a default configuration for PHP, so you can find the php.ini file in the default Ubuntu directory:

`/etc/php/8.0/fmp/php.ini`

And you can change the ram assigned in the var:

`memory_limit = 8G ;`

And no, you don't need to change the limits.conf file to change the php conf.

I hope this explanation can help you

Best
