### ISSUE TITLE
Issues installing Dedalo: Failed opening config_auto.php

### ISSUE THREAD

**Issue by Angel-Vila** [renderpci/dedalo#49]
I've been trying to install Dedalo in an Ubuntu 20.04 Virtual Machine, and after finally being able to set the Apache server, and adjusting the php and Apache configurations, I'm getting this error when I open the website through my web browser:

> Ops.. [Fatal Error] include(): Failed opening '/var/www/html/dedalo/lib/dedalo/config/config_auto.php' for inclusion (include_path='.:/usr/share/php')

I've checked the files in that folder, and there's no config_auto.php. Is there something I'm missing, or is it a different kind of error?
Thank you.

**Comment by renderpci** [comment]
Hi Angel-Vila

Seems that PHP doesn't have permission to write inside `../dedalo/lib/dedalo/config` directory.

The 'config_auto.php' is generated and saved when you try to access to Dédalo for first time, it's generated and saved by tool_administration.php. Usually, if you don't have the file it's because PHP can't save it.

Review the permissions of the PHP user to get access to the entire Dédalo directory tree (not only for the config directory, Dédalo need access / write / change / etc, other directories as `../media`)

Best

**Comment by Angel-Vila** [comment]
Changing the ownership of the Dedalo folder to PHP user solved this error, but now I'm having a too many redirects error when I try to access the Dedalo application. Any idea of what could the issue be? Thank you.

**Comment by renderpci** [comment]
Hi Angel-Vila

Very difficult to say with this information... Please, try to define more clear your questions, sending the log of http or php, if you are using php-fpm, version of apache, php, vhosts configuration, etc... 

Well, things to review:

1 Apache DocumentRoot:
The DocumentRoot in Apache vhosts cannot be pointing to the /dedalo directory, the correct path must be:
`/my_path_to_documet_root/my_document_root/`

In your case:
`/var/www/html/`

**NOT:**
`/var/www/html/dedalo`

The main /dedalo directory need to be accessed by the http calls like:
https://mydomain.com/dedalo

The call:
https://mydomain.com/dedalo/lib/dedalo/main/?m=tool_administration&t=dd242

need to be correct

2 Check the Apache log
Read the Apache log with something as:

`tail -f /var/log/apache/httpd.log`

and re-do the call in the browser. The terminal will show the apache error and what's happened in the call. (If you need, you can send here this error log...)

3 Try to install 'manually' going to the administation_tool:

Replace with your domain or ip this call
http://mydomain.com/dedalo/lib/dedalo/main/?m=tool_administration&t=dd242

I hope that it can help and work...

Best

**Comment by Angel-Vila** [comment]
Okay, let's see. I have tried moving the dedalo folder directly to the html one, so now my tree is /var/www/html/[all the Dedalo folder contents]. When I try to connect, however, the direction is http://[my domain]/lib/dedalo/main/?t=dd242.

As for the error log, this is what comes out:

> [Mon May 02 12:23:49.476342 2022] [php7:notice] [pid 37872] [client 192.168.1.100:51560] ERROR: <span class='error'>Ops.. [Error]2 pg_query() expects parameter 1 to be resource, bool given</span><pre>Array\n(\n    [type] => 2\n    [message] => pg_query() expects parameter 1 to be resource, bool given\n    [file] => /var/www/html/dedalo/lib/dedalo/search/class.search_development2.php\n    [line] => 3761\n)\n</pre>
[Mon May 02 12:23:49.476354 2022] [php7:notice] [pid 37872] [client 192.168.1.100:51560] ERROR: <span class='error'>Ops.. [Error]2 pg_last_error(): No PostgreSQL link opened yet</span><pre>Array\n(\n    [type] => 2\n    [message] => pg_last_error(): No PostgreSQL link opened yet\n    [file] => /var/www/html/dedalo/lib/dedalo/search/class.search_development2.php\n    [line] => 3763\n)\n</pre>
[Mon May 02 12:23:49.476373 2022] [php7:notice] [pid 37872] [client 192.168.1.100:51560] \n--> DUMP \n  Caller: /lib/dedalo/search/class.search_development2.php\n Line: 3763\n Inside method: add_column\n name: <strong> pg_last_error() ++ ALTER TABLE "jer_dd" ADD IF NOT EXISTS "properties" jsonb NULL;</strong>\n value: false\n type: boolean\n Caller2:  /var/www/html/dedalo/lib/dedalo/main/index.php\n Function: check_db_ready [Line: 31]
[Mon May 02 12:23:49.476386 2022] [php7:notice] [pid 37872] [client 192.168.1.100:51560] ERROR: <span class='error'>Ops.. [Error]1024 [add_column] Caught exception: Error Processing Request</span><pre>Array\n(\n    [type] => 1024\n    [message] => [add_column] Caught exception: Error Processing Request\n    [file] => /var/www/html/dedalo/lib/dedalo/search/class.search_development2.php\n    [line] => 3767\n)\n</pre>
[Mon May 02 12:23:49.476452 2022] [php7:notice] [pid 37872] [client 192.168.1.100:51560] ERROR: <span class='error'>Ops.. [Error]2 pg_query() expects parameter 1 to be resource, bool given</span><pre>Array\n(\n    [type] => 2\n    [message] => pg_query() expects parameter 1 to be resource, bool given\n    [file] => /var/www/html/dedalo/lib/dedalo/db/class.RecordDataBoundObject.php\n    [line] => 127\n)\n</pre>
[Mon May 02 12:23:49.476475 2022] [php7:notice] [pid 37872] [client 192.168.1.100:51560] ERROR: <span class='error'>Ops.. [Error]2 pg_fetch_assoc() expects parameter 1 to be resource, null given</span><pre>Array\n(\n    [type] => 2\n    [message] => pg_fetch_assoc() expects parameter 1 to be resource, null given\n    [file] => /var/www/html/dedalo/lib/dedalo/db/class.RecordDataBoundObject.php\n    [line] => 150\n)\n</pre>
[Mon May 02 12:23:49.476506 2022] [php7:notice] [pid 37872] [client 192.168.1.100:51560] ERROR: <span class='error'>Ops.. [Error]2 pg_query() expects parameter 1 to be resource, bool given</span><pre>Array\n(\n    [type] => 2\n    [message] => pg_query() expects parameter 1 to be resource, bool given\n    [file] => /var/www/html/dedalo/lib/dedalo/db/class.RecordDataBoundObject.php\n    [line] => 127\n)\n</pre>
[Mon May 02 12:23:49.476517 2022] [php7:notice] [pid 37872] [client 192.168.1.100:51560] ERROR: <span class='error'>Ops.. [Error]2 pg_fetch_assoc() expects parameter 1 to be resource, null given</span><pre>Array\n(\n    [type] => 2\n    [message] => pg_fetch_assoc() expects parameter 1 to be resource, null given\n    [file] => /var/www/html/dedalo/lib/dedalo/db/class.RecordDataBoundObject.php\n    [line] => 150\n)\n</pre>
[Wed May 04 12:10:12.440440 2022] [mpm_prefork:notice] [pid 37868] AH00171: Graceful restart requested, doing restart
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 127.0.1.1. Set the 'ServerName' directive globally to suppress this message

From what I can see, this seems like issues with PostrgreSQL, but I can't seem to find what's wrong. Sorry if I'm asking too many things by the way, this is my first time setting up a proper server, so to speak.

**Comment by renderpci** [comment]
Hi Angel-Vila

Don't worry to ask. :-) and never say sorry to ask, asking is the way to knowledge ;-)
And much better with this info !

Well, I see that you don't have the config4_db.php file configured with your database connection... The installation file require that you have the config4_db.php with your DDBB connection.

You need to read, in our webpage, how you can config Dédalo:

https://dedalo.dev/v5_config

You need to read the topics:
1 Rename the Dédalo config files (changing the sample config files to production config files)
2 Changing the parameters of Dédalo config DB file (to get access to the DDBB, for now only the postreSQL part, mySQL is used only for publication)

When you have access to Dédalo, you will need to read:
3 Changing the parameters of global Dédalo config file. (config your installation with you own custom params)

I hope that it will be clear.

Best
