### ISSUE TITLE
Menu with valid permissions not shown

### ISSUE THREAD

**Issue by FelipeBergua** [renderpci/dedalo#50]
Hi,
We have a problem with area_activity. All user profile in our instalation have the correct permissión but the menu item is not showned.
 
![Captura](https://user-images.githubusercontent.com/38144118/167116615-7314b8b1-67b2-47ce-9234-d8d4187bd1ef.JPG)

Help wanted, thank you very much.

**Comment by renderpci** [comment]
Hi FelipeBergua

Seems that you have the config4_areas.php denying access to "activities" area (dd69)

You would need to read the "Changing the parameters of Dédalo config Areas file" in our website:
https://dedalo.dev/v5_config#dd1100_730

the last part of the config article; "Allowing / denying access variables" and remove the deny rule for 'dd69'.

And maybe you can add the "numisdata1200" in the array of skip_tipos var:
`define('DEDALO_ENTITY_MENU_SKIP_TIPOS', serialize( array( 'numisdata1200' )));`
in config4.php file. It will remove the "NUMISDATA" (numisdata1200) level of the menu tree. It's just "aesthetic" but....

Note: in DEDALO_ENTITY_MENU_SKIP_TIPOS var, you could have some other tipos, don't remove it, add the new one at the end.

I hope that is clear.

Best

**Comment by FelipeBergua** [comment]
Hi
It work`s. 
Thank you very much
