### ISSUE TITLE
Acces Dedalo 6

### ISSUE THREAD

**Issue by pricua** [renderpci/dedalo#51]
Hi,

We would like to start testing version 6 in order to test the correct functioning of new features in this version.

We have updated a Dédalo installation to version 6 beta and when trying to access an incorrect user/password error is appearing.

With this same username/password we can access the same installation with Dédalo 5 without any problem.

Has any modification been made in terms of access, password encryption,...? Or is it necessary to make an update on the BBDD to be able to use Dédalo 6?

Thanks

**Comment by renderpci** [comment]
Hi pricua

First, version 6 is in beta state, it's unstable and doesn't have all V5 functionalities.

And yes, you will need update you V5 installation, it will not compatible directly. In other words, the V6 database format is different from V5, and it's not possible share the DDBB of your installation between V5 and V6 simultaneously. I recommend duplicate your V5 DDBB and update the duplicate, maybe you can use something as:

`CREATE DATABASE dedalo_V6 TEMPLATE dedalo_v5;`

Second, the update is NOT finished and it's not fully tested. It could fail. Update with care and seeing the error_log of php.

Answering your specific question, no, the encryption has not changed, you have to be able to login in V6 before update the database.
BUT, ensure that you have the last V5 format of the data in administration panel:

The version has to be at least : v5.8.2

<img width="252" alt="Screenshot 2022-05-15 at 12 08 52" src="https://user-images.githubusercontent.com/8447635/168467726-3e56a69f-7e62-439d-b142-6a036a236033.png">

If you are using any other version before 5.8.2 of your data you would not able to login.

And you need to login **ONLY** with a root user, any other user account is not active before you update the DDBB, the user accounts in V5 format are disable.

Last but not least, your php version need to be 8.0 or newer. V6 will not compatible with PHP 7 or older and your PostgreSQL need to be 14.1 or newer, Dédalo V6 will not be compatible with PostgreSQL 13 or older.

Well if you have your system ready, I explain the process to update.
When you login in V6, you will see the red alert box saying that  you have the 5.8.2 version of you data.

<img width="364" alt="Screenshot 2022-05-15 at 12 09 31" src="https://user-images.githubusercontent.com/8447635/168467760-1a9eebbe-2fb0-43c2-a081-862b8790bb4c.png">

After login with root account you should go to the new administration panel.

`../dedalo/core/page/?t=dd770`

or doing a double click in the new "Developer" menu:

<img width="169" alt="Screenshot 2022-05-15 at 12 00 25" src="https://user-images.githubusercontent.com/8447635/168467842-1428689a-2bb1-43c1-a668-d19c1e90f8ab.png">

Lookup the "UPDATE DATA" panel.

<img width="311" alt="Screenshot 2022-05-15 at 12 04 14" src="https://user-images.githubusercontent.com/8447635/168467897-f22ab05a-e20b-46cd-803f-a02e99586d46.png">

And do the update process after the last script process:

<img width="160" alt="Screenshot 2022-05-15 at 12 04 21" src="https://user-images.githubusercontent.com/8447635/168467923-14dce130-95be-4af2-b5f8-d587be8fc997.png">

Cross your fingers and wait, the update take time and it depends of your amount of data, in out servers the process takes 1 second to update around 3.000 sections and update process, in a 500.000 sections installation it would takes around 15-20 min. be patient. You can see the process in the php log.
If everything went well, you will see the summary of the process with the  `result : true` saying that you have the data in V6.  If not, you will see a output with the error, see the php log and find the error. You can re-run the update scripts, it's safe run it again with some partial data updated, some data in V5 and some data in V6, don't worry about running the scripts again.

<img width="551" alt="Screenshot 2022-05-15 at 15 11 42" src="https://user-images.githubusercontent.com/8447635/168474620-b6e61b86-8f2a-41aa-b48b-89b7d80e4699.png">

Quit Dédalo and re-login with the right version of your DDBB. At this point you can login with other user accounts, but I recommend first login with root user to test that your data is correct.

<img width="361" alt="Screenshot 2022-05-15 at 12 22 21" src="https://user-images.githubusercontent.com/8447635/168468074-2e52206d-451c-4294-9f76-0ae4cf9a179a.png">

Done!

If you find errors updating, please comment it, or fixed it and pull request of your code. Thanks.

Best

**Comment by pricua** [comment]
Hello,

thanks for the reply. Do not worry, we know that it is a beta version and therefore it is not stable and may have untested errors, it is normal :)

The machine we were testing Dédalo 6 on did not meet the minimum requirements so we have moved it to a new machine with php 8 and PostgreSQL 14.

Now, when trying to access, the login window is not displayed and the following error is recorded in the log: (this error did not appear on the previous machine)

[Wed May 18 17:16:[43.586993 2022](callto:43.586993 2022)] [php:notice] [pid 760234] [client XXX] <span class='error'>Ops.. [Exception] Undefined constant &quot;DEDALO_LOCALE&quot;</span><pre>Error Object\n(\n    [message:protected] => Undefined constant "DEDALO_LOCALE"\n    [string:Error:private] => \n    [code:protected] => 0\n    [file:protected] => /dedalo6/core/common/js/environment.js.php\n    [line:protected] => 126\n    [trace:Error:private] => Array\n        (\n            [0] => Array\n                (\n                    [file] => /dedalo6/core/common/js/environment.js.php\n                    [line] => 137\n                    [function] => {closure}\n                )\n\n        )\n\n    [previous:Error:private] => \n)\n</pre>, referer: http://xxx/dedalo6/core/page/

Does this error sound familiar to you? Where is this constant defined and what value does it have to have? In the config files we have seen that it does not appear.

Thanks again.

**Comment by renderpci** [comment]
Hi pricua

Upppsss!, it seems that new constants for the new config.php are not inside the sample.config.php

We need to review all the sample.config.php with the new additions... but for now, you can add manually the DEDALO_LOCALE to your config.php, something like:

	`define('DEDALO_LOCALE'	, 'en-GB');`

In 'lang' part, around line 214 of the sample.config.php
Note: for Spanish you can change the value to: 'es-ES' or for català: 'ca-ES'

If you see other similar error, tell us, it's possible that we may have forgotten other constants in the sample.config.php file.

Best
