### ISSUE TITLE
Install and test Dédalo 4 : success config but no access to main page

### ISSUE THREAD

**Issue by anisDev-Pr** [renderpci/dedalo#52]
I've been trying to install Dedalo 4 on debian 11.3 with the configuration mentioned in the doc, after configuring the 3 files config4.php, config4_areas.php and config4_db.php.
I opened on the browser the url "http:/ /192.168.1.33/dedalo5/lib/dedalo/install/" and it gives:
Installation help
  Installation info: https://dedalo.dev/v5
  Config info: https://dedalo.dev/v5_config
Test setup
Configuration test passed for entity: dedalo
1. Install Dédalo DDBB
Install DDBB source file: /var/www/html/dedalo5/install/db/dedalo4_install.pgsql.gz
DB Config:
DEDALO_HOSTNAME_CONN: localhost
DEDALO_DB_PORT_CONN: 5432
DEDALO_SOCKET_CONN:
DEDALO_DATABASE_CONN: dedalo_db
DEDALO_USERNAME_CONN: dedalo_user

But the Main url "http://192.168.1.33/dedalo5/lib/dedalo/main/?t=dd242" does not display anything (This page does not work)

![page_install](https://user-images.githubusercontent.com/105807160/169091337-092eac5e-d3d6-47d0-9ca0-05e20b500cf2.png)
![page_main](https://user-images.githubusercontent.com/105807160/169091344-e5404a15-1653-4770-a156-0a0a98faa09e.png)

Thank you for  helping.

**Comment by anisDev-Pr** [comment]
Thank you very much renderpci for your answer,
I checked, the confi4_auto.php file was created correctly.
I changed dedalo5 folder name with dedalo and tried with url "http://192.168.1.33/dedalo/lib/dedalo/main/?m=tool_administration&t=dd242" and still got error.

![page_confi1](https://user-images.githubusercontent.com/105807160/169263366-27aed2b3-051a-4746-9e74-5e678ad4be7c.png)
![page_config_areas](https://user-images.githubusercontent.com/105807160/169263376-1c0dee21-1f82-4f79-a3fb-41c3e5645769.png)
![page_main1](https://user-images.githubusercontent.com/105807160/169263380-bb54cab0-1db4-4eb9-9972-c61be79c8638.png)

Thanks.

**Comment by renderpci** [comment]
Hi anisDev-Pr

First: seem that you added $areas_allow with the dd242 value, but the array values need to be a string: **['dd242']** not [dd242].
Second: it's not necessary allow the dd242 section, it's the main section for inventory and it's allowed by default.

Questions: 
Can you login?
Has the installation process been successful?
Do you have the httpdocs pointed to directory of the httpdocs (something as /var/www/)? (inside this directory pointed by apache hosts you should have dedalo/lib/dedalo)
Could you send the php error log with the error done by you request?
Can you check that PostgreSQL has the dédalo installation structure done? (In your DDBB you should have some "matrix_*" tables and a "jer_dd" table with data)

Best

**Comment by anisDev-Pr** [comment]
Thanks renderpci for your help ,

I just checked Postgresql and I have the dedalo_db database with all the tables, but I don't have the right to the tables for the user "dedalo_user" . By adding the right the problem is solved and I have the login interface, so I  create a password for the user "root"  then by connecting with "root" it gives this:

![dedalo_home](https://user-images.githubusercontent.com/105807160/169278861-73480f65-66e7-4add-8ad6-dabc8d55b9a7.png)
![dedalo_install01](https://user-images.githubusercontent.com/105807160/169278867-f00df2d1-3794-4e18-a9f3-a8f377c666da.png)

**Comment by renderpci** [comment]
Hi anisDev-Pr

Happy to see your Dédalo installation ready! :-)

Note: I see that you want to work in French. Pourriez-vous aider à traduire l'interface Dédalo? ce n'est pas entièrement traduit en français...

Best

**Comment by anisDev-Pr** [comment]
Hi renderpci,

Thnanks renderpci for Helping me.

Yes normally I will make a site of "MANAGING CULTURAL HERITAGE ARCHIVES" like https://monedaiberica.org/v2/
Do you have an idea or a document that describe how to make a publication with dedalo ?

Thanks.

**Comment by renderpci** [comment]
Hi anisDev-Pr

Well, if you have ready you data you will need to config the Dédalo API.
General info:
https://dedalo.dev/publication_api#dd1100_80

Set up:
https://dedalo.dev/publication_api_set_up

Prepare you publication environment:
https://dedalo.dev/publication_api_configuration#dd1100_90

Publish your data and access to it by the API:
https://dedalo.dev/media/pdf/30
https://dedalo.dev/media/pdf/31

But

The first step is configure and setup the config files to get access to the numisdata ontology, if you want to work with numismatic data.
Read this https://dedalo.dev/v5_config#dd1100_730
in the part of 
DEFAULT VARIABLES -> DEDALO_PREFIX_TIPOS

you will need to add 'numisdata' to the array and if you want, remove the other heritage tipos, something like:

`define('DEDALO_PREFIX_TIPOS', serialize([ 'dd', 'rsc', 'hierarchy', 'lg', 'numisdata ]));`

This setting say that your Dédalo installation will be sync with numismatic ontology.
The next action should be sync your ontology with the new setting;
1 save the config4.php with the new params
2 login with root account
3 open the admin panel:
4 click "update structure"

<img width="156" alt="Screenshot 2022-05-19 at 16 52 36" src="https://user-images.githubusercontent.com/8447635/169326172-5dd7bc2a-c89e-4466-881b-3ad4e6e44534.png">

5 if all go right your Dédalo installation will load the numisdata ontology, then, logout an login. Check if the "catalogue" menu has the Mints, Types, Archive, Hoards... sections 
 
<img width="118" alt="Screenshot 2022-05-19 at 16 53 59" src="https://user-images.githubusercontent.com/8447635/169326443-096417a4-c7b6-48f9-a39c-a918bcf03833.png">

(It could be inside of Cultural->Material->Mobable Heritage->Numisdata)

Then Dédalo will be ready to work with numismatic heritage... 
Next Spets:
- Create users, profiles to access to the sections / fields ... etc
- Import or create your data.
- Publish your data
- Access with the Public API
- Build the public web site

Ufff... 

Too long to explain...

Best

**Comment by anisDev-Pr** [comment]
Thanks renderpci,

I will read and try to apply all this step by step, it requires a little of concentration.

Thanks for all.

**Comment by anisDev-Pr** [comment]
Hi renderpci,

I tried to connect to the dedalo on the url "http://192.168.1.33/dedalo/lib/dedalo/main/?m=tool_administration&t=dd242&menu=1" to access the menu, but it contains  errors:
Ops.. [Error]2 include(/var/www/html/dedalo/lib/dedalo/ZipArchive/class.ZipArchive.php): failed to open stream: No such file or directory
Array
(
    [type] => 2
    [message] => include(/var/www/html/dedalo/lib/dedalo/ZipArchive/class.ZipArchive.php): failed to open stream: No such file or directory
    [file] => /var/www/html/dedalo/lib/dedalo/config/class.loader.php
    [line] => 84
)
![dedalo_menu01](https://user-images.githubusercontent.com/105807160/169504465-d9c74c3e-962a-460a-8dca-cf4f38aaed11.png)

Do you have any ideas ?

Thanks.

**Comment by renderpci** [comment]
Hi anisDev-Pr

Seem that you don't have the zip library for php.

If you are using Ubuntu you can try to install php and all modules that Dédalo will need with:

apt install php8.0 php8.0-cli php8.0-common php8.0-mysql php8.0-pgsql php8.0-gd php8.0-mbstring php8.0-xml php8.0-pspell php8.0-tidy php8.0-bcmath php8.0-imap php8.0-soap php8.0-opcache php8.0-fpm php8.0-zip php8.0-curl

Best

**Comment by Ons-BenBrahim** [comment]
Hi ! I am begginner with Dedalo i installed it recently , but i didn't understand from where can i start using it ! for example how can i create a template ?
If anybody have a tutorial or a documentation explaining this i will be grateful !!
Thanx
