### ISSUE TITLE
Import Toponomy problem

### ISSUE THREAD

**Issue by FelipeBergua** [renderpci/dedalo#54]
Hi,

We need to import 36 toponomies to our installation and I get a problem in the first attempt with de1. See capture below.

<img width="1375" alt="Captura" src="https://user-images.githubusercontent.com/38144118/174858990-73614ad5-0c7a-489f-9510-25fc7a5fccaf.PNG">

Help wanted, please!

**Comment by devpacdd** [comment]
Hi Felipe,
you need to un-gzip the files before they are ready to import from psql ;-)

Something like this might work:

`gunzip us1.copy.gz | psql dedalo_db_wondercoins -U dedalo -p 5432 -h localhost -c "\copy matrix_hierarchy(section_id, section_tipo, datos) from us1.copy"`

**BUT**

I recommend you this:

We recently updated the v5 code adding a more easy tool to manage hierarchy country tonomys.
Yo can update your running Dédalo installation code from master.render.es using the Admin utils panel to the latest version and follow the web page instructions:
[https://dedalo.dev/importing_hierarchies](https://dedalo.dev/importing_hierarchies)

**Comment by FelipeBergua** [comment]
Hi,
It works, thank you very much.
