### ISSUE TITLE
Dedalo 

### ISSUE THREAD

**Issue by Ons-BenBrahim** [renderpci/dedalo#57]
Hi ! I am begginner with Dedalo i installed it recently , but i didn't understand from where can i start using it ! for example how can i create a template ?
If anybody have a tutorial or a documentation explaining this i will be grateful !! 
Thanx

**Comment by renderpci** [comment]
Welcome [Ons-BenBrahim](https://github.com/Ons-BenBrahim) !

Some questions:
Do you have Dédalo installed?
If your Dédalo installation is ready, you could use it as normal with the heritage field that you want to work.
You can read the first steps guide:
https://dedalo.dev/first_steps

When you talk about the template, are you referred a web template? or do you want to change the ontology?

Ontology -> work system. It is used to create data structure of the catalog (fields, relations between data, etc).
Web template -> diffusion.  It is used to show the partial or complete data of the catalog that can be public.

If you want to create a web template you can see:
https://dedalo.dev/api_publication_templates

Best
