### ISSUE TITLE
Getting database connection error

### ISSUE THREAD

**Issue by FelipeBergua** [renderpci/dedalo#58]
Hello,

This is the error
![Captura](https://user-images.githubusercontent.com/38144118/188954965-00789a73-9085-4e42-8886-f45697a6355f.PNG)

I ask for help because I don´t know whats wrong this time. I only know I'm close to the solution.
Please, thanks for any comment.

**Comment by renderpci** [comment]
Hi [FelipeBergua](https://github.com/FelipeBergua)

Seems an error in your config4_db.php, maybe you have a typo in the database name, or pw... if all ok inside config4_db.php, review your postgreSQL instance, try:

`systemctl status postgresql`

If the PostgreSQL instance is running, try to login to the Database with the config4_db.php parameters:

 check if you can login with user postgreSQL
`su - postgres `
`psql yourdDDBB`

If you can login to the database, review the .pgpass file info [here](https://www.postgresql.org/docs/14/libpq-pgpass.html).

If all fail... check the log of PostgreSQL and PHP and write to me....

I hope that it will clear

Best

**Comment by FelipeBergua** [comment]
Hi again and thank you for the quick response.
It works... for a while. 
The config4_db.php had a old postgres db password from our actual production server.
I made a rsync to the new server of dedalo folder yesterday.
Now, I put another distinct root password for dedalo in the new server and I get this errors in the web browser....

![Captura](https://user-images.githubusercontent.com/38144118/189088150-c754c013-40bf-4243-b76d-87f4b751574f.PNG)

Maybe another configuration inherited from production server is making something wrong?
Please, help!

Thank you, best regards

**Comment by renderpci** [comment]
Hi [Feipe](https://github.com/FelipeBergua)

Seems that you are restore your old database with permissions. You can do that when you have the same permissions between installations, but I recommend you to remove the old permission in the import process at any case!, because PostgreSQL will refresh the roles and will have the new DDBB more "clean".

Try to import the backup with `--no-owner --no-privileges --clean`  something like:

`pg_restore --host localhost --port 5432 --username "MyNewUsername" --dbname "MyNewDDBB" --role "YourNewUser" --no-owner --no-privileges --clean --verbose "My_OLD_DDBB.backup"`

It will import a clean DDBB and will assign the new privileges. PostgreSQL documentation about pg_restore [here](https://www.postgresql.org/docs/current/app-pgrestore.html)

I hope it will useful.

Best

**Comment by FelipeBergua** [comment]
Hi

I tried to import the backup but get some errors during the process (see .txt)
[pg_restore verbose.txt](https://github.com/renderpci/dedalo/files/9529537/pg_restore.verbose.txt)

When access with web browser I get this... 
<img width="612" alt="Captura" src="https://user-images.githubusercontent.com/38144118/189193549-b6c8db8f-a8d8-4fdb-85fd-ac4067cdbd08.PNG">

Thank you for your dedication and patience.

**Comment by renderpci** [comment]
Hi [FelipeBergua](https://github.com/FelipeBergua)

Seems that you are importing the backup in a **NOT CLEAN** DDBB that has the incorrect privileges:

you can read in the log, some error as:

```
1--> pg_restore: dropping SEQUENCE matrix_activity_section_id_seq
2--> pg_restore: from TOC entry 209; 1259 16513 SEQUENCE matrix_activity_section_id_seq dedalo
3--> pg_restore: error: could not execute query: ERROR:  must be owner of sequence matrix_activity_section_id_seq
```
In line 1 says: the DDBB has matrix_activity_section_id_seq and need to drop it.
In line 2 inform of the command and it will be execute with dedalo user.
in line 3 says: the owner is incorrect and it can not delete the sequence.

I want to remark the error: **...must be owner of sequence...**

In other words, you have a dirty database with different owner, and PosgtgreSQL can not delete the structure before import the new one.

Posible solution: delete the database and create new one, a clean database, and import the backup without permissions.

Try: 
Delete database
`DROP DATABASE MyDDBB`

Create the user (if you don't have one created) if postgreSQL say that your user exist.... it's ok, it's not necessary create new one or change the user... I add this step for other users that could want create the database from scratch
`CREATE USER MyUser PASSWORD 'MyPW';`

Create new DDBB:
```
CREATE DATABASE MyCleanDDBB
WITH ENCODING='UTF8'
OWNER=MyUser
CONNECTION LIMIT=-1
TABLESPACE=pg_default;
```
if you want, you can add a comment of the database:

```
COMMENT ON DATABASE MyCleanDDBB
IS 'Dédalo: Cultural Heritage and Oral Memory management system';
```

And import the backup

I hope help you

Best

**Comment by FelipeBergua** [comment]
Hi

Than you very much, problem solved.
I'm sorry to post this so late.

Best regards
