### ISSUE TITLE
Import Toponomy final step

### ISSUE THREAD

**Issue by FelipeBergua** [renderpci/dedalo#62]
Hi

First I create the toponymy into the Hierarchy menu into Thesaurus. Then I import the data in postgres database (dz1.copy file)
But now I can´t find de "Dedalo Counters State" in the administration tool to update the counters  (maybe I'm blind)
Sorry, can you show me where is that?

Thank you very much!

As always, best regards.

**Comment by renderpci** [comment]
Hi FelipeBergua

In recent versions (>5.8.0) we implemented a more easy way to install toponymies.

You only need to call to install script: 

`https://my_dedalo_server.org/dedalo/install`
(replace my_dedalo_server.org by you own domain)

And you will see the page with all toponomies:
<img width="1155" alt="Screenshot 2023-03-06 at 17 23 13" src="https://user-images.githubusercontent.com/8447635/223170502-2bb09537-ad7e-4a0b-a512-eaef9e0985e6.png">

And select the country that you want to install and click the "install hierarchy" button... 
Note: you will need to be logged as root to install.

If you want to do manually, as you ask, I think that you only need to activate the hierarchy to show it in the thesaurus.

<img width="367" alt="Screenshot 2023-03-06 at 17 32 43" src="https://user-images.githubusercontent.com/8447635/223172526-12df0ff3-c6a1-4081-b5a6-df6e377b83e8.png">


I hope that it will be clear.

Best

**Comment by FelipeBergua** [comment]
Hi

It works, thank you!
